rom_dict = {'りゃ': 'dx y aa', 
'りぇ': 'dx y eh', 
'りゅ': 'dx y uw', 
'りょ': 'dx y ao', 
'ぴゃ': 'p y aa', 
'ぴぇ': 'p y eh', 
'ぴゅ': 'p y uw', 
'ぴょ': 'p y ao', 
'ふゃ': 'f y aa', 
'ふゅ': 'f y uw', 
'ふぇ': 'f eh', 
'ぎゃ': 'g y aa', 
'ぎゅ': 'g y uw', 
'ぎぇ': 'g y eh', 
'ぎょ': 'g y ao', 
'ひゃ': 'h y aa', 
'ひゅ': 'h y uw', 
'ひぇ': 'h y eh', 
'ひょ': 'h y ao', 
'きゃ': 'k y aa', 
'きぇ': 'k y eh', 
'きゅ': 'k y uw', 
'きょ': 'k y ao', 
'びゃ': 'b y aa', 
'びゅ': 'b y uw', 
'びぇ': 'b y eh', 
'びょ': 'b y ao', 
'にゃ': 'n y aa', 
'にゅ': 'n y uw', 
'にぇ': 'n y eh', 
'にょ': 'n y ao', 
'みゃ': 'm y aa', 
'みゅ': 'm y uw', 
'みぇ': 'm y eh', 
'みょ': 'm y ao', 
'てぃ': 't aa', 
'てゅ': 't y uw', 
'てぇ': 't y eh', 
'てょ': 't y ao', 
'てゃ': 't y aa', 
'でぃ': 'd aa', 
'でゅ': 'd y uw', 
'でぇ': 'd y eh', 
'でょ': 'd y ao', 
'でゃ': 'd y aa', 
'づぁ': 'dz aa', 
'ぢぇ': 'dz eh', 
'づぉ': 'dz ao', 
'づ': 'dz uw', 
'ぢ': 'dz aa', 
'か': 'k aa', 
'き': 'k iy', 
'く': 'k uw', 
'け': 'k eh', 
'こ': 'k ao', 
'た': 't aa', 
'とぅ': 't uw', 
'て': 't eh', 
'と': 't ao', 
'ど': 'd ao', 
'だ': 'd aa', 
'どぅ': 'd uw', 
'で': 'd eh', 
'つぁ': 't s aa', 
'つぃ': 't s iy', 
'つぇ': 't s eh', 
'つぉ': 't s ao', 
'つ': 't s uw', 
'さ': 's aa', 
'すぃ': 's iy', 
'す': 's uw', 
'せ': 's eh', 
'そ': 's ao', 
'ふぁ': 'f aa', 
'ふぃ': 'f iy', 
'ふょ': 'f y ao', 
'ふぉ': 'f ao', 
'ふ': 'f uw', 
'が': 'g aa', 
'ぎ': 'g iy', 
'ぐ': 'g uw', 
'げ': 'g eh', 
'ご': 'g ao', 
'じゃ': 'j aa', 
'じゅ': 'j uw', 
'じぇ': 'j eh', 
'じょ': 'j ao', 
'じ': 'j iy', 
'ざ': 'z aa', 
'ずぃ': 'z iy', 
'ず': 'z uww', 
'ぜ': 'z eh', 
'ぞ': 'z ao', 
'ヴぁ': 'v aa', 
'ヴぃ': 'v iy', 
'ヴぇ': 'v eh', 
'ヴぉ': 'v ao', 
'ヴ': 'v uww', 
'ば': 'b aa', 
'び': 'b iy', 
'ぶ': 'b uww', 
'べ': 'b eh', 
'ぼ': 'b ao', 
'ぱ': 'p aa', 
'ぴ': 'p iy', 
'ぷ': 'p uww', 
'ぺ': 'p eh', 
'ぽ': 'p ao', 
'な': 'n aa', 
'に': 'n iy', 
'ぬ': 'n uww', 
'ね': 'n eh', 
'の': 'n ao', 
'ま': 'm aa', 
'み': 'm iy', 
'む': 'm uww', 
'め': 'm eh', 
'も': 'm ao', 
'ら': 'dx aa', 
'り': 'dx iy', 
'る': 'dx uw', 
'れ': 'dx eh', 
'ろ': 'dx ao', 
'わ': 'w aa', 
'うぃ': 'w iy', 
'うぅ': 'w uw', 
'うぇ': 'w eh', 
'うぉ': 'w ao', 
'や': 'y aa', 
'ゆ': 'y uw', 
'いぇ': 'y eh', 
'よ': 'y ao', 
'いぃ': 'y iy', 
'しゃ': 'sh aa', 
'しゅ': 'sh uw', 
'しぇ': 'sh eh', 
'しょ': 'sh ao', 
'し': 'sh iy', 
'ちゃ': 'ch aa', 
'ちゅ': 'ch uw', 
'ちぇ': 'ch eh', 
'ちょ': 'ch ao', 
'ち': 'ch iy', 
'は': 'hh aa', 
'ひ': 'hh iy', 
'へ': 'hh eh', 
'ほぅ': 'hh uw', 
'ほ': 'hh ao',
'あ': 'aa', 
'い': 'iy', 
'う': 'uw', 
'え': 'eh', 
'ん': 'nn', 
'お': 'ao'}